name: Stochss-Compute Docker container build & push
on:
  push:
    branches:
    # which one?
      # - "main"
      # - "dev"
      - "mdip/feature/46-use-github-actions-to-automate-docker-images-pushes"
jobs:
# QEMU?
  build-push:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ” Branch >>> ${{ github.ref }}"
      - run: echo "ğŸ” Repository >>> ${{ github.repository }}"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - run: echo "ğŸ‰ Docker Buildx setup triggered by ${{ github.event_name }}."
      - run: echo "ğŸ§ This job is now running on ${{ runner.os }}"
      - name: checkout
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.MD_DOCKERHUB_USERNAME }}"
          password: ${{ secrets.MD_DOCKERHUB_TOKEN }}"
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./api.dockerfile
          tags: stochss/stochss-compute:latest
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      # - run: echo "ğŸ–¥ï¸ Workflow."
